[server]
headless = true
address = "0.0.0.0"
port = 8501
maxUploadSize = 200

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#5A87FF"
backgroundColor = "#030711"
secondaryBackgroundColor = "#091327"
textColor = "#F7F9FF"
font = "sans serif"
